### ISSUE TITLE
Toppings (Delta + LoRA support)

### ISSUE THREAD

**Issue by xzyaoi** [eth-easl/Scratchpad#6]
### Stage 1 (in PR #10):
- [x] System Controller for Topping Registration
- [x] Toppings Manager (Detects, Loads, Swap toppings)
- [x] Kernels (Delta + LoRA kernel @enothum)
- [x] Statistics Logger

### Stage 2:

- [ ] FP16 full swap support
- [ ] Correctness verification
- [ ] Improved stats logger

### Step 3:
- [ ] Tensor Parallelism support
